### ISSUE TITLE
Doesn't work for pined tabs

### ISSUE THREAD

**Issue by olegantonyan** [hensm/disable_tab_detach#2]
FF 61.0.1 64bit Linux
Doesn't work for pined tabs. And stops working for regular tabs after trying to detach pined tab

**Comment by sabinich** [comment]
FF 62.0, 64bit Windows10
Also doesn't work for pinned tabs.

**Comment by hensm** [comment]
Fixed: e91a5a2

**Comment by olegantonyan** [comment]
Great! Thank you! When will it be released?

**Comment by hensm** [comment]
I uploaded a new version to AMO yesterday, so it should be available right now.
