### ISSUE TITLE
publish release notes for about:addons 

### ISSUE THREAD

**Issue by atomGit** [hensm/disable_tab_detach#3]
hi Matt

something i do myself and recommend others do is to always read the release notes and re-check privacy policies when updating any add-on, the problem being that a dev can sell or monetize the add-on which usually leads to unethical bullshit

so - i respectfully ask that you consider publishing the release notes so that they are available from about:addons -> avaliable updates -> show release notes

**Comment by hensm** [comment]
I usually add release notes. Added some just now, but I've had issues with them actually showing up on release pages. Only seems to work around half the time.

So, hopefully they're visible for you now, but if not, I'm not going to spend any more time on it.
