### ISSUE TITLE
If there are several pinned tabs, only works for the rightmost one

### ISSUE THREAD

**Issue by bogbert** [hensm/disable_tab_detach#7]
If there are several pinned tabs, the extension only works for the rightmost one, the other ones can be detached normally
version 0.0.4 tested

**Comment by hensm** [comment]
Ah, that happens because the tab is unpinned once it's detached and you can't move an unpinned tab before a pinned tab.

Fixed — fe05f64

**Comment by bogbert** [comment]
version 0.0.5 just installed, problem gone, thanks
